# This is a basic workflow to help you get started with Actions

name: DOcker build and test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: repository ausschecken
        uses: actions/checkout@v4

      - name: docker installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: docker image bauen
        run: |
          docker build -t oldschool-demo-mika_schulte-image

      - name: container starten
        run: |
          docker run -d --name demo_container oldschool-demo-mika_schulte-image

      - name: ausgabe testen
        run: |
          docker logs demo_container

      - name: Container starten & testen 
        run: | 
          output=$(docker run oldschool-demo-mika_schulte-image) 
          echo "$output" 
          if [ "$output" != "OldSchool GmbH â€“ automatischer Build erfolgreich!" ]; then 
            echo "Test fehlgeschlagen!" 
            exit 1 
          fi 
